# _config.yml


title: "Services - Products - Projects"
description: "Operational information quickly at hand regarding the active services at FarmaFlux."
url: "https://apb-flux.github.io/"
baseurl: ""  # Set to "/repo-name" if hosted in a subdirectory

remote_theme: just-the-docs/just-the-docs

# Enable search
search_enabled: true

nav:
  - title: "Technical Documentation"
    children:
      - title: "PharmForms"
        url: "/Technical Documentation/PharmForms/"
      - title: "PHM Portal"
        children:
          - title: "VACCINATION"
            url: "/Technical Documentation/PHM Portal/VACCINATION/README.md"
            children:
              - title: "PharmForm PHM"
                url: "/Technical Documentation/PHM Portal/VACCINATION/PharmForm_PHM.md"
              - title: "Testing PHM"
                url: "/Technical Documentation/PHM Portal/VACCINATION/Testing_PHM.md"
                
