title: "FarmaFlux Services Programs Projects"
description: "For FLUX, a known path for you, the tangled web unraveled"
theme: just-the-docs

# URL settings
baseurl: "" # e.g. /docs if hosted at https://username.github.io/docs
url: "https://apb-flux.github.io/"

# Enable search
search_enabled: true

# Navigation settings
nav_sort: case_insensitive
aux_links:
  "GitHub Repository":
    - "https://github.com/username/repository"

# Footer
footer_content: "© 2025 My Project. All rights reserved."

# Color scheme (optional)
color_scheme: light

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
