# _config.yml


title: "Services - Products - Projects"
description: "Operational information quickly at hand regarding the active services at FarmaFlux."
url: "https://apb-flux.github.io/"
baseurl: ""  # Set to "/repo-name" if hosted in a subdirectory

theme: "docsy-jekyll"

# Docsy Jekyll settings
repository_url: "https://github.com/apb-flux/farmaflux-pub"
repository_branch: "main"
edit_page_button: true

# Optional: Google Analytics, Disqus, etc.
# google_analytics: UA-XXXXXXXX-X
# disqus_shortname: your-shortname

# Navigation is handled in _data/navigation.yml
